### ISSUE TITLE
Accessible aria-props?

### ISSUE THREAD

**Issue by httpete** [system-props/system-props#13]
Is there an easy way to tap into all of the aria- props from system-props?

**Comment by roginfarrer** [comment]
Can you elaborate a bit more? Can you use some code snippets to explain what you want to happen?

**Comment by httpete** [comment]
So I am adding a <div role="listbox"> or <div aria-selected="true"> and you get so used to adding props it just feels natural to want to leverage system-props.

**Comment by roginfarrer** [comment]
I'm still not sure what you are requesting. System Props doesn't have a say about HTML attributes. You can still build a component with system props and other valid HTML attributes.

So we can get on the same page, let's try this:

1. What did you do?
2. What did you expect to happen?
3. What actually happened?

**Comment by httpete** [comment]
You are correct I opened this with the wrong question. Sorry.
