### ISSUE TITLE
SVG stroke and fill props values on DOM node

### ISSUE THREAD

**Issue by jmakGH** [system-props/system-props#29]
Looks like the stroke and fill props that get threaded through to the underlying DOM node don't receive the transformed values.

<img width="450" alt="Screen Shot 2021-04-19 at 8 20 34 AM" src="https://user-images.githubusercontent.com/3829337/115261025-22b3d600-a0e8-11eb-9a38-1ad08867efe3.png">

**Comment by roginfarrer** [comment]
I think this is expected. The transform happens within the styled-component, rendered by the component that receives the `fill` and `stroke` props. I think ideally those attributes would not get passed down to the underlying element, and let the styling be applied by CSS.

You can use `shouldForwardProp` exported from this package alongside styled-components' or Emotion's APIs for configuring the should forward prop behavior. You can see it used in the example: https://github.com/system-props/system-props/blob/46db72be7584d68483ca4c733643cc6ca12c4f3c/example/src/box-styled-components.tsx#L9
