### ISSUE TITLE
TypeScript error for number props since v0.19

### ISSUE THREAD

**Issue by Kerumen** [system-props/system-props#42]
Since latest release `v0.19` it's not possible to write `marginLeft={2}` anymore. We get a TS error:

```
Type '2' is not assignable to type 'SystemProp<MarginLeft<0 | (string & {})>> | undefined'.
```

**Comment by roginfarrer** [comment]
Can you share what your theme interface looks like, as well as your `createSystem` config? Should `2` be `2px` or a theme token?

**Comment by Kerumen** [comment]
Here are the relevant part of my theme:

```
const theme = {
  space: [0, 4, 8, 16, 32, 64, 128, 256],
}
```

And my `createSystem` config is:

```
const system = createSystem({
  strict: false,
  tokenPrefix: "noprefix",
});
```

`2` should be a theme token and `8px` in my case. As it is in the docs:

![image](https://user-images.githubusercontent.com/5436545/120100634-0329b780-c142-11eb-803c-c2e80d250b95.png)


PS: The value is working fine, I'm just talking about the type error that appeared in `v0.19`.

**Comment by roginfarrer** [comment]
Can you share the TypeScript definition for your theme? Does it look like this?

```ts
interface Theme {
  space: [number, number, number, number, number, number, number, number]
}
```

**Comment by Kerumen** [comment]
Yes, it's `space: number[];`

**Comment by roginfarrer** [comment]
That might be the issue. Can you try using the snippet I provided above (using a tuple instead of an unspecified length array of numbers?

**Comment by Kerumen** [comment]
I have a different error now:

```
Type '2' is not assignable to type 'SystemProp<MarginLeft<0 | (string & {})> | "$1" | "$2" | "$3" | "$4" | "$0" | "$5" | "$6" | "$7"> | undefined'.
```

**Comment by roginfarrer** [comment]
I've had this issue before, but I cannot reproduce in v19. Here's a codesandbox, where I think the types are pretty happy https://codesandbox.io/s/dreamy-wood-9l0vz?file=/src/App.tsx

Are you passing `'noprefix'` to your types? If you're using `SpaceProps` or `AllSystemProps` you'll want to give them that change, too. Here's an example:

```typescript
// Makes the JS work for no-prefix
const system = createSystem({tokenPrefix: 'noprefix'})

// Makes the types work for no-prefix
interface BoxProps extends AllSystemProps<'noprefix'> {}
```

**Comment by Kerumen** [comment]
That as it! I'm using `SpaceProps` and if I use `SpaceProps<'noprefix'>` it works. Thanks!
