### ISSUE TITLE
`_disabled` attribute is not working

### ISSUE THREAD

**Issue by Kerumen** [system-props/system-props#43]
In its current form, the `_disabled` pseudo selector is not working. It generates a class `.hash [disabled]` targeting the descendant element and not the disabled one.

To fix it, we should change it to

```
_disabled: '&[disabled], &[disabled]:hover, &[disabled]:focus, &[aria-disabled], &[aria-disabled]:hover, &[aria-disabled]:focus',
```

I don't know if you want me to open the PR? I can do it, and we should also add a test to ensure everything is working as intended.

**Comment by roginfarrer** [comment]
Ya that would be great!
